language: python
python:
	- "2.6"
	- "2.7"
	- "3.2"
sudo: false
dist: trusty

install:
	- pip install -r requirements.txt

script: 
	- python build.py

deploy:
	provider: script
	
	skip_cleanup: true
	on:
		branch: master

